# Generated by Django 3.2.7 on 2021-09-04 12:34

from django.db import migrations, models
import users.users_validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=255, verbose_name='Отчество')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Электронная почта')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[users.users_validators._phone_validation], verbose_name='Телефонный номер')),
                ('position', models.PositiveSmallIntegerField(choices=[('Учитель', 1), ('Руководитель направления', 2), ('Администратор', 3), ('Директор', 4)], verbose_name='Должность')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
