# Generated by Django 3.2.7 on 2021-09-06 19:14

from django.db import migrations, models
import django.db.models.deletion
import users.models
import users.users_validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=255, verbose_name='Отчество')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Электронная почта')),
                ('image', models.ImageField(blank=True, upload_to=users.models.create_path_media_user, verbose_name='Изображение')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[users.users_validators._phone_validation], verbose_name='Телефонный номер')),
                ('position', models.PositiveSmallIntegerField(choices=[(1, 'Учитель'), (2, 'Руководитель направления'), (3, 'Администратор')], verbose_name='Должность')),
                ('is_account_confirmation', models.BooleanField(default=False, verbose_name='Подтверждение аккаунта в системе')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Сотрудники школы',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('staffuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.staffuser')),
                ('parents', models.JSONField(default={'parent1': {'name': '', 'phone': ''}}, verbose_name='Родители')),
                ('start_learning', models.DateField(auto_now=True, verbose_name='Начало обучения')),
                ('end_learning', models.DateField(blank=True, default='2030-01-01', verbose_name='Конец обучения')),
            ],
            options={
                'verbose_name': 'Учащиеся',
            },
            bases=('users.staffuser',),
        ),
    ]
