# Generated by Django 3.2.7 on 2021-09-04 13:34

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffuser',
            name='image',
            field=models.ImageField(blank=True, upload_to=users.models.create_path_media_user, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='position',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Учитель'), (2, 'Руководитель направления'), (3, 'Администратор'), (4, 'Директор')], verbose_name='Должность'),
        ),
    ]
