# Generated by Django 3.2.7 on 2021-09-14 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210909_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='end_learning',
            field=models.DateField(blank=True, null=True, verbose_name='Конец обучения'),
        ),
    ]
