# Generated by Django 3.2.7 on 2021-09-14 19:41

from django.db import migrations, models
import users.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_student_end_learning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentsstudent',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, unique=True, validators=[users.utils.phone_validation], verbose_name='Телефонный номер'),
        ),
    ]
