# Generated by Django 3.2.7 on 2021-09-14 19:43

from django.db import migrations, models
import users.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_parentsstudent_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentsstudent',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, unique=True, validators=[users.utils._phone_validation], verbose_name='Телефонный номер'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, unique=True, validators=[users.utils._phone_validation], verbose_name='Телефонный номер'),
        ),
    ]
