# Generated by Django 3.2.7 on 2021-09-19 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_structure', '0005_alter_educationalсlass_name'),
        ('users', '0006_alter_staffuser_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='educational_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='school_structure.educationalсlass', verbose_name='Образовательный класс'),
        ),
    ]
