# Generated by Django 3.2.7 on 2021-09-19 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_student_educational_class'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
