# Generated by Django 3.2.7 on 2021-09-19 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_structure', '0005_alter_educationalсlass_name'),
        ('users', '0008_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_learning', models.DateField(auto_now=True, verbose_name='Начало обучения')),
                ('end_learning', models.DateField(blank=True, null=True, verbose_name='Конец обучения')),
                ('educational_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='school_structure.educationalсlass', verbose_name='Образовательный класс')),
                ('parents', models.ManyToManyField(blank=True, to='users.ParentsStudent', verbose_name='Родители')),
                ('score', models.ManyToManyField(blank=True, related_name='students', to='school_structure.ScoreStudent', verbose_name='оценки')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Учащийся',
            },
        ),
    ]
