# Generated by Django 3.2.7 on 2021-09-27 19:25

from django.db import migrations, models
import users.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210926_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=users.utils.create_path_media_user, verbose_name='Изображение'),
        ),
    ]
