# Generated by Django 3.2.7 on 2021-10-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='parents',
            field=models.ManyToManyField(blank=True, null=True, to='users.ParentsStudent', verbose_name='Родители'),
        ),
    ]
