# Generated by Django 3.2.7 on 2021-10-23 14:33

from django.db import migrations, models
import users.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_student_parents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, validators=[users.utils.phone_validation], verbose_name='Телефонный номер'),
        ),
    ]
