# Generated by Django 3.2.7 on 2021-10-24 14:31

from django.db import migrations, models
import users.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentsstudent',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, validators=[users.utils.phone_validation], verbose_name='Телефонный номер'),
        ),
    ]
