# Generated by Django 3.2.7 on 2021-10-24 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_parentsstudent_phone_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parentsstudent',
            unique_together=set(),
        ),
    ]
