# Generated by Django 3.2.7 on 2021-10-25 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_parentsstudent_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parentsstudent',
            unique_together=set(),
        ),
    ]
