# Generated by Django 3.2.7 on 2021-10-25 20:33

from django.db import migrations, models
import users.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_parentsstudent_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentsstudent',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, unique=True, validators=[users.utils.phone_validation], verbose_name='Телефонный номер'),
        ),
    ]
