# Generated by Django 3.2.7 on 2021-11-13 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_parentsstudent_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parentsstudent',
            unique_together={('first_name', 'last_name', 'phone_number')},
        ),
    ]
