# Generated by Django 3.2.7 on 2021-11-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_parentsstudent_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registration_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата регистрации'),
        ),
    ]
