# Generated by Django 3.2.7 on 2021-11-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_user_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registration_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата регистрации'),
        ),
    ]
