# Generated by Django 3.2.7 on 2021-11-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_user_registration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffuser',
            name='receiver',
            field=models.BooleanField(default=True, verbose_name='Получать пьсьмо'),
        ),
        migrations.AddField(
            model_name='staffuser',
            name='time_recipient_emails',
            field=models.TimeField(default='10:00', verbose_name='Время получения письма'),
        ),
    ]
