# Generated by Django 3.2.7 on 2021-11-18 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20211115_2019'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parentsstudent',
            unique_together=set(),
        ),
    ]
