version: '3.7'
services:
  backend:
    build: .
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py loaddata dbv2.json && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/usr/src/manage_school
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - postgres
  postgres:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=ManageSchool
  redis:
    image: redis:alpine
    restart: always
    expose:
      - '6379'
    ports:
      - '6379:6379'
  celery:
    build: .
    command: celery -A config worker -l info
    volumes:
      - .:/usr/src/manage_school/celery
    depends_on:
      - postgres
      - redis
  celery-beat:
    build: .
    command: celery -A config beat -l info
    volumes:
      - .:/usr/src/manage_school/celery
    depends_on:
      - postgres
      - redis
volumes:
  postgres_data: