# Generated by Django 3.2.7 on 2021-09-09 19:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название школы')),
                ('addres', models.CharField(max_length=300, verbose_name='Адресс школы')),
                ('email', models.EmailField(max_length=100, verbose_name='Электронный адрес')),
            ],
            options={
                'verbose_name': 'Образовательная организации',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название Предмета')),
            ],
            options={
                'verbose_name': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название темы')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_structure.topic')),
            ],
            options={
                'verbose_name': 'Темы занятий',
            },
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')], verbose_name='День недели')),
                ('start_time', models.TimeField(verbose_name='Начало работы')),
                ('end_time', models.TimeField(blank=True, verbose_name='Конец работы')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_structure.subject', verbose_name='Предмет')),
                ('topic', models.ManyToManyField(blank=True, null=True, to='school_structure.Topic', verbose_name='Темы занятий')),
            ],
            options={
                'verbose_name': 'Расписание',
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='topic',
            field=models.ManyToManyField(blank=True, null=True, to='school_structure.Topic', verbose_name='Тема занятий'),
        ),
        migrations.CreateModel(
            name='ScoreStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('date', models.DateField(blank=True, verbose_name='Дата')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_structure.subject', verbose_name='Предмет')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_structure.topic', verbose_name='Тема занятий')),
            ],
            options={
                'verbose_name': 'Оценка',
            },
        ),
        migrations.CreateModel(
            name='EducationalСlass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название класса')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='school_structure.school', verbose_name='Школа')),
                ('timetable', models.ManyToManyField(blank=True, related_name='classes', to='school_structure.TimeTable', verbose_name='Расписание')),
            ],
            options={
                'verbose_name': 'Образовательные классы',
            },
        ),
        migrations.CreateModel(
            name='DirectionScience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название направления')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='school_structure.school', verbose_name='Школа')),
            ],
            options={
                'verbose_name': 'Учебные направления',
            },
        ),
    ]
