# Generated by Django 3.2.7 on 2021-09-04 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DirectionScience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название направления')),
                ('slug', models.SlugField(max_length=300, verbose_name='url направления')),
            ],
            options={
                'verbose_name': 'Учебные направления',
            },
        ),
        migrations.CreateModel(
            name='SchoolStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название школы')),
                ('slug', models.SlugField(max_length=300, verbose_name='url школы')),
                ('addres', models.CharField(max_length=300, verbose_name='Адресс школы')),
                ('email', models.EmailField(max_length=100, verbose_name='Электронный адрес')),
                ('directions_science', models.ManyToManyField(blank=True, null=True, to='school_structure.DirectionScience', verbose_name='Направления обучения')),
            ],
            options={
                'verbose_name': 'Образовательные организации',
            },
        ),
        migrations.CreateModel(
            name='EducationalСlass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название класса')),
                ('slug', models.SlugField(max_length=300, verbose_name='url класса')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='school_structure.schoolstructure', verbose_name='Школа')),
            ],
            options={
                'verbose_name': 'Образовательные классы',
            },
        ),
        migrations.AddField(
            model_name='directionscience',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='school_structure.schoolstructure', verbose_name='Школа'),
        ),
    ]
