# Generated by Django 3.2.7 on 2021-09-06 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectionScience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название направления')),
                ('slug', models.SlugField(max_length=300, verbose_name='url направления')),
            ],
            options={
                'verbose_name': 'Учебные направления',
            },
        ),
        migrations.CreateModel(
            name='EducationalСlass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название класса')),
                ('slug', models.SlugField(max_length=300, verbose_name='url класса')),
            ],
            options={
                'verbose_name': 'Образовательные классы',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название Предмета')),
            ],
            options={
                'verbose_name': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название темы')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_structure.topic')),
            ],
            options={
                'verbose_name': 'Темы занятий',
            },
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='День занятий')),
                ('start_time', models.TimeField(verbose_name='Начало занятий')),
                ('end_time', models.TimeField(verbose_name='Конец занятий')),
                ('educational_class', models.ManyToManyField(blank=True, null=True, related_name='timetable', to='school_structure.EducationalСlass', verbose_name='Образовательные классы')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_structure.subject', verbose_name='Предмет')),
                ('teacher', models.ManyToManyField(blank=True, null=True, related_name='timetable', to=settings.AUTH_USER_MODEL, verbose_name='Учитель(я)')),
                ('topic', models.ManyToManyField(blank=True, null=True, to='school_structure.Topic', verbose_name='Темы занятий')),
            ],
            options={
                'verbose_name': 'Расписание',
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='topic',
            field=models.ManyToManyField(blank=True, null=True, to='school_structure.Topic', verbose_name='Тема занятий'),
        ),
        migrations.CreateModel(
            name='SchoolStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название школы')),
                ('slug', models.SlugField(max_length=300, verbose_name='url школы')),
                ('addres', models.CharField(max_length=300, verbose_name='Адресс школы')),
                ('email', models.EmailField(max_length=100, verbose_name='Электронный адрес')),
                ('directions_science', models.ManyToManyField(blank=True, null=True, to='school_structure.DirectionScience', verbose_name='Направления обучения')),
            ],
            options={
                'verbose_name': 'Образовательные организации',
            },
        ),
        migrations.AddField(
            model_name='educationalсlass',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='school_structure.schoolstructure', verbose_name='Школа'),
        ),
        migrations.AddField(
            model_name='educationalсlass',
            name='student',
            field=models.ManyToManyField(blank=True, related_name='classes', to='users.Student', verbose_name='Учащиеся'),
        ),
        migrations.AddField(
            model_name='directionscience',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='school_structure.schoolstructure', verbose_name='Школа'),
        ),
    ]
