# Generated by Django 3.2.7 on 2021-09-15 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_structure', '0003_alter_subject_direction_science'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalсlass',
            name='name',
            field=models.CharField(max_length=300, unique=True, verbose_name='Название класса'),
        ),
    ]
