# Generated by Django 3.2.7 on 2021-09-25 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_structure', '0005_alter_educationalсlass_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalсlass',
            name='timetable',
            field=models.ManyToManyField(blank=True, null=True, related_name='classes', to='school_structure.TimeTable', verbose_name='Расписание'),
        ),
    ]
