# Generated by Django 3.2.7 on 2021-10-02 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_structure', '0007_alter_timetable_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorestudent',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='scorestudent',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='school_structure.subject', verbose_name='Предмет'),
        ),
    ]
