# Generated by Django 3.2.7 on 2021-10-11 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_structure', '0008_auto_20211002_2139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scorestudent',
            options={'verbose_name': 'Оценка', 'verbose_name_plural': 'Оценки'},
        ),
        migrations.AlterModelOptions(
            name='timetable',
            options={'verbose_name': 'Расписание', 'verbose_name_plural': 'Расписание'},
        ),
    ]
