# Generated by Django 3.2.7 on 2021-10-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_structure', '0009_auto_20211011_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Конец работы'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Начало работы'),
        ),
    ]
