# Generated by Django 3.2.7 on 2021-10-24 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_structure', '0010_auto_20211014_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='addres',
            new_name='address',
        ),
    ]
