# Generated by Django 3.2.7 on 2021-11-18 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время отправки уведомления'),
        ),
    ]
