# Generated by Django 3.2.7 on 2021-11-18 19:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0002_email_date_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Email',
            new_name='Notifications',
        ),
    ]
