# Generated by Django 3.2.7 on 2021-11-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_rename_email_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Статус отправки'),
        ),
    ]
